#obj-$(CONFIG_ARCH_MSM8974) += htc_8974-panel.o

obj-$(CONFIG_MACH_M8) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_DUG) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WHL) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WL) += htc_m8-panel.o

obj-$(CONFIG_MACH_MEM_UL) += htc_mem-panel.o

obj-$(CONFIG_MACH_A5) += htc_a5-panel.o
obj-$(CONFIG_MACH_EYE_UL) += htc_eye-panel.o
obj-$(CONFIG_MACH_MEC_UL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_DWG) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_DUG) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_TL) += htc_mec-panel.o
obj-$(CONFIG_MACH_MEC_WHL) += htc_mec-panel.o