#ifndef _ASM_POWERPC_AUXVEC_H
#define _ASM_POWERPC_AUXVEC_H

#define AT_DCACHEBSIZE		19
#define AT_ICACHEBSIZE		20
#define AT_UCACHEBSIZE		21
#define AT_IGNOREPPC		22

#define AT_SYSINFO_EHDR		33

#define AT_VECTOR_SIZE_ARCH 6 

#endif
